### ISSUE TITLE
Please add .NET Core Test Explorer into your recommend pack!

### ISSUE THREAD

**Issue by blackie1019** [doggy8088/netcore-extension-pack#2]
As we known, testing is important as development, and integration with testing tool is key point to continue delivery good quality outcome. 

Please review below tools and add it as recommend tool to save the time of browsing testing case in plain text file. 

[.NET Core Test Explorer](https://marketplace.visualstudio.com/items?itemName=formulahendry.dotnet-test-explorer)

**Comment by doggy8088** [comment]
Added.  Thanks!
